import React from 'react';

/**
 * @typedef {Object} ToolRoute
 * @property {string} id
 * @property {string[]} aliases
 * @property {string} title
 * @property {string} tooltip
 * @property {string} category
 * @property {string} description
 * @property {string[]} searchMetadata
 * @property {string | null} subGroup
 * @property {string} iconKey
 * @property {() => Promise<{ default: React.ComponentType<any> }>} loader
 * @property {Record<string, unknown>} componentProps
 * @property {boolean} staticLayout
 * @property {boolean} navigationVisible
 * @property {React.LazyExoticComponent<React.ComponentType<any>>} component
 */

const definitions = [
  {
    id: 'tool-home',
    aliases: [],
    title: 'Dashboard',
    tooltip: 'Dashboard',
    category: 'home',
    description: 'Small Web Tools dashboard.',
    searchMetadata: ['Dashboard', 'Home'],
    subGroup: null,
    iconKey: 'tool-home',
    loader: () => import('./components/HomeGrid.jsx'),
    componentProps: {},
    staticLayout: false,
    navigationVisible: false,
  },
  {
    id: "tool-slash",
    aliases: [],
    title: "Slashes Converter",
    tooltip: "Slashes Converter",
    category: "developer",
    description: "Switch \\ to /.",
    searchMetadata: ["Slashes Converter","Slashes Converter","Switch \\ to /."],
    subGroup: null,
    iconKey: "tool-slash",
    loader: () => import("./components/SlashesConverter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-wc",
    aliases: [],
    title: "Word Counter",
    tooltip: "Word Counter",
    category: "text",
    description: "Calculate words, characters, sentences, and reading time.",
    searchMetadata: ["Word Counter","Word Counter","Calculate words, characters, sentences, and reading time."],
    subGroup: null,
    iconKey: "tool-wc",
    loader: () => import("./components/WordCounter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-casing",
    aliases: [],
    title: "Casing Switcher",
    tooltip: "Casing Switcher",
    category: "text",
    description: "Support full sentence, single  words, specific term, etc.",
    searchMetadata: ["Casing Switcher","Casing Switcher","Support full sentence, single  words, specific term, etc."],
    subGroup: null,
    iconKey: "tool-casing",
    loader: () => import("./components/CasingSwitcher.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-typing",
    aliases: [],
    title: "Typing Speed Test",
    tooltip: "Typing Speed Test",
    category: "text",
    description: "Test and improve your typing speed with English prose, code, or custom templates.",
    searchMetadata: ["Typing Speed Test","Typing Speed Test","Test and improve your typing speed with English prose, code, or custom templates."],
    subGroup: null,
    iconKey: "tool-typing",
    loader: () => import("./components/TypingSpeedTest.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-color",
    aliases: [],
    title: "Color Converter",
    tooltip: "Color Converter",
    category: "media",
    description: "Transfer and select colors between HEX, RGB, and other formats.",
    searchMetadata: ["Color Converter","Color Converter","Transfer and select colors between HEX, RGB, and other formats."],
    subGroup: null,
    iconKey: "tool-color",
    loader: () => import("./components/ColorConverter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-ascii",
    aliases: [],
    title: "ASCII Converter",
    tooltip: "ASCII Converter",
    category: "developer",
    description: "Text to ASCII codes; ASCII codes to text.",
    searchMetadata: ["ASCII Converter","ASCII Converter","Text to ASCII codes; ASCII codes to text."],
    subGroup: null,
    iconKey: "tool-ascii",
    loader: () => import("./components/AsciiConverter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-unicode",
    aliases: [],
    title: "Unicode Converter",
    tooltip: "Unicode Converter",
    category: "developer",
    description: "Text to Unicode; Unicode to text.",
    searchMetadata: ["Unicode Converter","Unicode Converter","Text to Unicode; Unicode to text."],
    subGroup: null,
    iconKey: "tool-unicode",
    loader: () => import("./components/UnicodeConverter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-url",
    aliases: [],
    title: "URL Encoder & Decoder",
    tooltip: "URL Encoder & Decoder",
    category: "developer",
    description: "Encode or decode URLs and Chinese addresses with UTF-8 percent-encoding.",
    searchMetadata: ["URL Encoder","URL Decoder","Percent encoding","Chinese address","UTF-8 URL"],
    subGroup: null,
    iconKey: "tool-url",
    loader: () => import("./components/UrlEncoderDecoder.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-markdown",
    aliases: [],
    title: "Markdown Previewer",
    tooltip: "Markdown Previewer",
    category: "developer",
    description: "Edit, upload, preview, and download Markdown files locally.",
    searchMetadata: ["Markdown Previewer","Markdown Editor","MD Preview","Edit, upload, preview, and download Markdown files locally."],
    subGroup: null,
    iconKey: "tool-markdown",
    loader: () => import("./components/MarkdownPreviewer.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-fontextractor",
    aliases: [],
    title: "Font Extractor",
    tooltip: "Website Font Extractor",
    category: "developer",
    description: "Inspect bounded font declarations from a public website without downloading font files.",
    searchMetadata: ["Font Extractor","Website Font Extractor","Inspect bounded font declarations from a public website without downloading font files."],
    subGroup: null,
    iconKey: "tool-fontextractor",
    loader: () => import("./components/WebsiteFontExtractor.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-base",
    aliases: [],
    title: "Base Converter",
    tooltip: "Base Converter",
    category: "developer",
    description: "Base conversion between binary, octal, decimal, and hexadecimal.",
    searchMetadata: ["Base Converter","Base Converter","Base conversion between binary, octal, decimal, and hexadecimal."],
    subGroup: null,
    iconKey: "tool-base",
    loader: () => import("./components/BaseConverter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-folder-analyzer",
    aliases: [],
    title: "Folder Analyzer",
    tooltip: "Folder Structure Analyzer",
    category: "developer",
    description: "Obtain the folder structure by one click.",
    searchMetadata: ["Folder Analyzer","Folder Structure Analyzer","Obtain the folder structure by one click."],
    subGroup: null,
    iconKey: "tool-folder-analyzer",
    loader: () => import("./components/FolderAnalyzer.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-dna",
    aliases: [],
    title: "DNA/RNA Converter",
    tooltip: "DNA/RNA Converter",
    category: "bioinfo",
    description: "Swap 5'/3' directions and show the anti-sense brand. Support with the figure.",
    searchMetadata: ["DNA/RNA Converter","DNA/RNA Converter","Swap 5'/3' directions and show the anti-sense brand. Support with the figure."],
    subGroup: null,
    iconKey: "tool-dna",
    loader: () => import("./components/DnaConverter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-codon",
    aliases: [],
    title: "Codon Table",
    tooltip: "RNA Codon Table",
    category: "bioinfo",
    description: "Find and learn amino acid with interactive.",
    searchMetadata: ["Codon Table","RNA Codon Table","Find and learn amino acid with interactive."],
    subGroup: null,
    iconKey: "tool-codon",
    loader: () => import("./components/CodonTable.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-phred",
    aliases: [],
    title: "Phred Scale Converter",
    tooltip: "Mapping Quality & Phred Scale Converter",
    category: "bioinfo",
    description: "Convert SNP/base-call and mapping-quality Phred scores to error probabilities.",
    searchMetadata: ["Phred Scale Converter","Mapping quality","SNP calling","Base quality","Error probability"],
    subGroup: null,
    iconKey: "tool-phred",
    loader: () => import("./components/PhredScaleConverter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-iplookup",
    aliases: [],
    title: "IP Lookup",
    tooltip: "IP Lookup",
    category: "network",
    description: "Identify geographical location, timezone, ISP, and coordinates for any IP address.",
    searchMetadata: ["IP Lookup","IP Lookup","Identify geographical location, timezone, ISP, and coordinates for any IP address."],
    subGroup: null,
    iconKey: "tool-iplookup",
    loader: () => import("./components/IpLookup.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-speedtest",
    aliases: [],
    title: "Speed Test",
    tooltip: "Network Speed Test",
    category: "network",
    description: "Test the real-time network speed and latency.",
    searchMetadata: ["Speed Test","Network Speed Test","Test the real-time network speed and latency."],
    subGroup: null,
    iconKey: "tool-speedtest",
    loader: () => import("./components/NetworkSpeedTest.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-imgmeta",
    aliases: [],
    title: "Image Metadata",
    tooltip: "Image Metadata",
    category: "media",
    description: "Extract and analyze EXIF, ICC, GPS, and custom camera metadata from image files locally.",
    searchMetadata: ["Image Metadata","Image Metadata","Extract and analyze EXIF, ICC, GPS, and custom camera metadata from image files locally."],
    subGroup: null,
    iconKey: "tool-imgmeta",
    loader: () => import("./components/ImgMeta.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-docmeta",
    aliases: ["tool-officemeta"],
    title: "Documents Metadata",
    tooltip: "Documents Metadata Reader",
    category: "media",
    description: "Show metadata from document files (Office, OpenOffice, and PDF).",
    searchMetadata: ["Documents Metadata","Documents Metadata Reader","Show metadata from document files (Office, OpenOffice, and PDF)."],
    subGroup: null,
    iconKey: "tool-docmeta",
    loader: () => import("./components/DocMeta.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-audiometa",
    aliases: [],
    title: "Audio Metadata",
    tooltip: "Audio Metadata Reader",
    category: "media",
    description: "Extract and analyze metadata tags, technical parameters entirely locally without upload.",
    searchMetadata: ["Audio Metadata","Audio Metadata Reader","Extract and analyze metadata tags, technical parameters entirely locally without upload."],
    subGroup: null,
    iconKey: "tool-audiometa",
    loader: () => import("./components/AudioMeta.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-videometa",
    aliases: [],
    title: "Video Metadata",
    tooltip: "Video Metadata Reader",
    category: "media",
    description: "Extract and analyze encoding format, resolution, and other parameters entirely locally without upload.",
    searchMetadata: ["Video Metadata","Video Metadata Reader","Extract and analyze encoding format, resolution, and other parameters entirely locally without upload."],
    subGroup: null,
    iconKey: "tool-videometa",
    loader: () => import("./components/VideoMeta.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-mediasplit",
    aliases: [],
    title: "Media Splitter",
    tooltip: "Media Splitter",
    category: "media",
    description: "Split a video's audio track and silent video track locally.",
    searchMetadata: ["Media Splitter","Media Splitter","Split a video's audio track and silent video track locally."],
    subGroup: null,
    iconKey: "tool-mediasplit",
    loader: () => import("./components/MediaSeparator.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-svg-png",
    aliases: [],
    title: "SVG to PNG",
    tooltip: "SVG to PNG Converter",
    category: "media",
    description: "Preview and export SVG artwork as a PNG entirely in your browser.",
    searchMetadata: ["SVG to PNG","SVG converter","PNG export","Rasterize vector image"],
    subGroup: null,
    iconKey: "tool-svg-png",
    loader: () => import("./components/SvgToPngConverter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-barcode",
    aliases: [],
    title: "Barcode Generator",
    tooltip: "Barcode Generator",
    category: "utilities",
    description: "Generate multiple format barcodes.",
    searchMetadata: ["Barcode Generator","Barcode Generator","Generate multiple format barcodes."],
    subGroup: "Utilities",
    iconKey: "tool-barcode",
    loader: () => import("./components/QrBarcodeGenerator.jsx"),
    componentProps: {"initialTab":"barcode"},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-currency",
    aliases: [],
    title: "Currency Converter",
    tooltip: "Currency Converter & Counter",
    category: "utilities",
    description: "Resource by Live API.",
    searchMetadata: ["Currency Converter","Currency Converter & Counter","Resource by Live API."],
    subGroup: "Calculation",
    iconKey: "tool-currency",
    loader: () => import("./components/CurrencyCounter.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-date",
    aliases: [],
    title: "Date & Time Counter",
    tooltip: "Date & Time Counter",
    category: "utilities",
    description: "Calculate differences between dates or times.",
    searchMetadata: ["Date & Time Counter","Date Counter","Time Counter","Calculate differences between dates or times."],
    subGroup: "Calculation",
    iconKey: "tool-date",
    loader: () => import("./components/DateCounter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-roman",
    aliases: [],
    title: "Roman Numeral Converter",
    tooltip: "Roman Numeral Converter",
    category: "utilities",
    description: "Convert between decimal numbers and canonical Roman numerals.",
    searchMetadata: ["Roman Numeral Converter","Roman numbers","Arabic numbers","Decimal to Roman","Roman numeral reference"],
    subGroup: "Calculation",
    iconKey: "tool-roman",
    loader: () => import("./components/RomanNumeralConverter.jsx"),
    componentProps: {},
    staticLayout: false,
    navigationVisible: true,
  },
  {
    id: "tool-password",
    aliases: [],
    title: "Password Generator",
    tooltip: "Secure Password Generator",
    category: "utilities",
    description: "Generate secure passwords. Use CSPRNG for generating.",
    searchMetadata: ["Password Generator","Secure Password Generator","Generate secure passwords. Use CSPRNG for generating."],
    subGroup: "Utilities",
    iconKey: "tool-password",
    loader: () => import("./components/PasswordGenerator.jsx"),
    componentProps: {"initialTab":"generate"},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-pwstrength",
    aliases: [],
    title: "Password Strength",
    tooltip: "Password Strength Checker",
    category: "utilities",
    description: "Check the passward is strengh or not.",
    searchMetadata: ["Password Strength","Password Strength Checker","Check the passward is strengh or not."],
    subGroup: "Utilities",
    iconKey: "tool-pwstrength",
    loader: () => import("./components/PasswordGenerator.jsx"),
    componentProps: {"initialTab":"check"},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-qrcode",
    aliases: [],
    title: "QR Code Generator",
    tooltip: "QR Code Generator",
    category: "utilities",
    description: "Create fully custimized QR code for free.",
    searchMetadata: ["QR Code Generator","QR Code Generator","Create fully custimized QR code for free."],
    subGroup: "Utilities",
    iconKey: "tool-qrcode",
    loader: () => import("./components/QrBarcodeGenerator.jsx"),
    componentProps: {"initialTab":"qr"},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-qrbarcodescan",
    aliases: [],
    title: "QR & Barcode Scanner",
    tooltip: "QR & Barcode Scanner",
    category: "utilities",
    description: "Scan the QR and barcodes. Support upload and camera.",
    searchMetadata: ["QR & Barcode Scanner","QR & Barcode Scanner","Scan the QR and barcodes. Support upload and camera."],
    subGroup: "Utilities",
    iconKey: "tool-qrbarcodescan",
    loader: () => import("./components/QrBarcodeScanner.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: "tool-wheel",
    aliases: [],
    title: "Random Wheel",
    tooltip: "Random Wheel",
    category: "utilities",
    description: "Set options, spin the wheel, and draw random items with optional single-draw elimination.",
    searchMetadata: ["Random Wheel","Random Wheel","Set options, spin the wheel, and draw random items with optional single-draw elimination."],
    subGroup: "Utilities",
    iconKey: "tool-wheel",
    loader: () => import("./components/RandomWheel.jsx"),
    componentProps: {},
    staticLayout: true,
    navigationVisible: true,
  },
  {
    id: 'privacy',
    aliases: [],
    title: 'Privacy & Network Services',
    tooltip: 'Privacy & Network Services',
    category: 'policy',
    description: 'Network service inventory, consent controls, and privacy policy.',
    searchMetadata: ['Privacy', 'Network Services', 'Consent'],
    subGroup: null,
    iconKey: 'privacy',
    loader: () => import('./components/PrivacyPolicy.jsx'),
    componentProps: {},
    staticLayout: true,
    navigationVisible: false,
  },
];

/** @type {ToolRoute[]} */
export const TOOL_ROUTES = definitions.map((route) => ({
  ...route,
  component: React.lazy(route.loader),
}));

export const NAVIGATION_ROUTES = TOOL_ROUTES.filter((route) => route.navigationVisible);
export const PUBLIC_ROUTE_IDS = TOOL_ROUTES.flatMap((route) => [route.id, ...route.aliases]);
export const STATIC_LAYOUT_IDS = new Set(
  TOOL_ROUTES.flatMap((route) => route.staticLayout ? [route.id, ...route.aliases] : []),
);

const routesById = new Map(
  TOOL_ROUTES.flatMap((route) => [route.id, ...route.aliases].map((id) => [id, route])),
);

export function getToolRoute(id) {
  return routesById.get(id) || null;
}
